### ISSUE TITLE
Convert from or to B is wrong

### ISSUE THREAD

**Issue by rbrunken** [void-gh/pwsh-data-size-unit-measure#1]
Because you have a case insensitive switch for the conversion of parameter From / To, B for Byte and b for bit are the same. So If I want to convert from B to MiB, the function converts from bit to MiB.

**Comment by void-gh** [comment]
Thanks for noticing the error. This was fixed in the latest update; however, the issue report wasn't acknowledged, and closed at the time the updated was posted.
